# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - StudentPerformanceML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dockermladitya.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_53a12ea383fa4148a40b4aa6d88f8b76 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c6029eb7311448f1acbe33175ccb3610 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dockermladitya.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_53a12ea383fa4148a40b4aa6d88f8b76 }}/endtoendmlstudentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'StudentPerformanceML'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a9cdd151f1c84842a9d77b77d79f9ab7 }}
        images: 'dockermladitya.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_53a12ea383fa4148a40b4aa6d88f8b76 }}/endtoendmlstudentperformance:${{ github.sha }}'